name: Hourly Maven Build

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分钟执行任务
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # 拉取代码到 CI 环境

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # 设置 JDK 版本
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  # 执行 Maven 构建命令

      - name: Run Tests
        run: mvn -B test # 执行测试，确保构建没有问题
